# Generated by Django 4.2.11 on 2024-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_contact_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
