# Generated by Django 4.2.11 on 2024-04-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='address',
        ),
    ]
